stages:
- build

centos8:
  stage: build
  image: gitlab-registry.cern.ch/linuxsupport/c8-base
  script:
    - dnf install -y git python rpm-build which dnf-plugins-core libuuid-devel
    - ci/gitlab-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r /root/rpmbuild/RPMS build/SRPMS ${CI_JOB_NAME}
  artifacts:
    paths:
    - "$CI_JOB_NAME"

